### ISSUE TITLE
Проблема при изменении переменной DIR_IMAGE

### ISSUE THREAD

**Issue by zed-yes** [ruOpenCart/opencart-russian-edition#1]
Здравствуйте!

Похоже, я наткнулся на ошибку.
в файлах config.php и admin/config.php определяется переменная DIR_IMAGE:
#define('DIR_IMAGE', 'D:/SERVER/www/image/');
Но, как оказалось, попытка ее изменить ни к чему хорошему не приводит.
Например, я у себя ее изменил в обоих файлах на 
define('DIR_IMAGE', 'D:/SERVER/www/_test/pictures/');

Я создал тестовый товар и проставил путь к его основной картинке в базе данных oc_product.image='apple_cinema_30.jpg'
Картинку я скопировал в новую папку:
D:\SERVER\www\_test\pictures\apple_cinema_30.jpg

Перезагрузил апач, обновил страницу, но картинка не отображается.
Хотя появилась папка D:\SERVER\www\_test\pictures\cache, в которой есть файл D:\SERVER\www\_test\pictures\cache\apple_cinema_30-500x500.jpg

Но при наведении курсора на странице товара видно, что картинка ищется по пути http://localhost/image/cache/apple_cinema_30-228x228.jpg
Т.е. несмотря на то, что в настройках я поставил вместо папки image другую папку, картинки пытаются считываться по старому пути

**Comment by Hkr32** [comment]
Это не относится к сборке. Это функционал opencart.
Попробуйте создать запрос тут https://github.com/opencart/opencart/issues
